export type GameTemplate = {
  id: string;
  name: string;
  category: string;
  docker_image: string;
  default_port: number;
  default_env: Record<string, string>;
  default_volumes: Record<string, string>;
};

export const GAME_CATALOG: GameTemplate[] = [
  // --- Featured (specialized images) ---
  {
    id: "minecraft",
    name: "Minecraft",
    category: "sandbox",
    docker_image: "itzg/minecraft-server:latest",
    default_port: 25565,
    default_env: {
      EULA: "TRUE",
      MEMORY: "4G",
      TYPE: "VANILLA",
    },
    default_volumes: { "/data/minecraft": "/data" },
  },
  {
    id: "valheim",
    name: "Valheim",
    category: "survival",
    docker_image: "lloesche/valheim-server:latest",
    default_port: 2456,
    default_env: {
      SERVER_NAME: "Valheim Server",
      WORLD_NAME: "Dedicated",
      SERVER_PASS: "${VALHEIM_SERVER_PASS}",
    },
    default_volumes: { "/data/valheim/config": "/config", "/data/valheim/data": "/opt/valheim" },
  },

  // --- FPS ---
  {
    id: "cs2server",
    name: "Counter-Strike 2",
    category: "fps",
    docker_image: "gameservermanagers/gameserver:cs2",
    default_port: 27015,
    default_env: {},
    default_volumes: { "/data/cs2": "/data" },
  },
  {
    id: "tf2server",
    name: "Team Fortress 2",
    category: "fps",
    docker_image: "gameservermanagers/gameserver:tf2",
    default_port: 27015,
    default_env: {},
    default_volumes: { "/data/tf2": "/data" },
  },
  {
    id: "gmodserver",
    name: "Garry's Mod",
    category: "fps",
    docker_image: "gameservermanagers/gameserver:gmod",
    default_port: 27015,
    default_env: {},
    default_volumes: { "/data/gmod": "/data" },
  },
  {
    id: "l4d2server",
    name: "Left 4 Dead 2",
    category: "fps",
    docker_image: "gameservermanagers/gameserver:l4d2",
    default_port: 27015,
    default_env: {},
    default_volumes: { "/data/l4d2": "/data" },
  },
  {
    id: "insurgencyserver",
    name: "Insurgency: Sandstorm",
    category: "fps",
    docker_image: "gameservermanagers/gameserver:ins",
    default_port: 27102,
    default_env: {},
    default_volumes: { "/data/insurgency": "/data" },
  },
  {
    id: "squadserver",
    name: "Squad",
    category: "fps",
    docker_image: "gameservermanagers/gameserver:squad",
    default_port: 7787,
    default_env: {},
    default_volumes: { "/data/squad": "/data" },
  },
  {
    id: "mordhauserver",
    name: "MORDHAU",
    category: "fps",
    docker_image: "gameservermanagers/gameserver:mh",
    default_port: 7777,
    default_env: {},
    default_volumes: { "/data/mordhau": "/data" },
  },
  {
    id: "pavlovserver",
    name: "Pavlov VR",
    category: "fps",
    docker_image: "gameservermanagers/gameserver:pv",
    default_port: 7777,
    default_env: {},
    default_volumes: { "/data/pavlov": "/data" },
  },

  // --- Survival ---
  {
    id: "rustserver",
    name: "Rust",
    category: "survival",
    docker_image: "gameservermanagers/gameserver:rust",
    default_port: 28015,
    default_env: {},
    default_volumes: { "/data/rust": "/data" },
  },
  {
    id: "arkserver",
    name: "ARK: Survival Evolved",
    category: "survival",
    docker_image: "gameservermanagers/gameserver:ark",
    default_port: 7777,
    default_env: {},
    default_volumes: { "/data/ark": "/data" },
  },
  {
    id: "dayzserver",
    name: "DayZ",
    category: "survival",
    docker_image: "gameservermanagers/gameserver:dayz",
    default_port: 2302,
    default_env: {},
    default_volumes: { "/data/dayz": "/data" },
  },
  {
    id: "sdtdserver",
    name: "7 Days to Die",
    category: "survival",
    docker_image: "gameservermanagers/gameserver:sdtd",
    default_port: 26900,
    default_env: {},
    default_volumes: { "/data/sdtd": "/data" },
  },
  {
    id: "pzserver",
    name: "Project Zomboid",
    category: "survival",
    docker_image: "gameservermanagers/gameserver:pz",
    default_port: 16261,
    default_env: {},
    default_volumes: { "/data/pz": "/data" },
  },
  {
    id: "unturnedserver",
    name: "Unturned",
    category: "survival",
    docker_image: "gameservermanagers/gameserver:ut",
    default_port: 27015,
    default_env: {},
    default_volumes: { "/data/unturned": "/data" },
  },
  {
    id: "dstserver",
    name: "Don't Starve Together",
    category: "survival",
    docker_image: "gameservermanagers/gameserver:dst",
    default_port: 10999,
    default_env: {},
    default_volumes: { "/data/dst": "/data" },
  },
  {
    id: "palserver",
    name: "Palworld",
    category: "survival",
    docker_image: "gameservermanagers/gameserver:pw",
    default_port: 8211,
    default_env: {},
    default_volumes: { "/data/palworld": "/data" },
  },
  {
    id: "ckserver",
    name: "Core Keeper",
    category: "survival",
    docker_image: "gameservermanagers/gameserver:ck",
    default_port: 27015,
    default_env: {},
    default_volumes: { "/data/corekeeper": "/data" },
  },
  {
    id: "btserver",
    name: "Barotrauma",
    category: "survival",
    docker_image: "gameservermanagers/gameserver:bt",
    default_port: 27015,
    default_env: {},
    default_volumes: { "/data/barotrauma": "/data" },
  },

  // --- Sandbox ---
  {
    id: "terrariaserver",
    name: "Terraria",
    category: "sandbox",
    docker_image: "gameservermanagers/gameserver:terraria",
    default_port: 7777,
    default_env: {},
    default_volumes: { "/data/terraria": "/data" },
  },
  {
    id: "fctrserver",
    name: "Factorio",
    category: "sandbox",
    docker_image: "gameservermanagers/gameserver:fctr",
    default_port: 34197,
    default_env: {},
    default_volumes: { "/data/factorio": "/data" },
  },
  {
    id: "sfserver",
    name: "Satisfactory",
    category: "sandbox",
    docker_image: "gameservermanagers/gameserver:sf",
    default_port: 7777,
    default_env: {},
    default_volumes: { "/data/satisfactory": "/data" },
  },
  {
    id: "ecoserver",
    name: "Eco",
    category: "sandbox",
    docker_image: "gameservermanagers/gameserver:eco",
    default_port: 3000,
    default_env: {},
    default_volumes: { "/data/eco": "/data" },
  },
  {
    id: "sbserver",
    name: "Starbound",
    category: "sandbox",
    docker_image: "gameservermanagers/gameserver:sb",
    default_port: 21025,
    default_env: {},
    default_volumes: { "/data/starbound": "/data" },
  },
  {
    id: "vrserver",
    name: "Vintage Story",
    category: "sandbox",
    docker_image: "gameservermanagers/gameserver:vr",
    default_port: 42420,
    default_env: {},
    default_volumes: { "/data/vintagestory": "/data" },
  },

  // --- Other ---
  {
    id: "avserver",
    name: "Assetto Corsa",
    category: "other",
    docker_image: "gameservermanagers/gameserver:ac",
    default_port: 9600,
    default_env: {},
    default_volumes: { "/data/assettocorsa": "/data" },
  },
  {
    id: "arma3server",
    name: "Arma 3",
    category: "other",
    docker_image: "gameservermanagers/gameserver:arma3",
    default_port: 2302,
    default_env: {},
    default_volumes: { "/data/arma3": "/data" },
  },
  {
    id: "mcbserver",
    name: "Minecraft Bedrock",
    category: "sandbox",
    docker_image: "gameservermanagers/gameserver:mcb",
    default_port: 19132,
    default_env: {},
    default_volumes: { "/data/mcbedrock": "/data" },
  },
  {
    id: "kfserver",
    name: "Killing Floor 2",
    category: "fps",
    docker_image: "gameservermanagers/gameserver:kf2",
    default_port: 7777,
    default_env: {},
    default_volumes: { "/data/kf2": "/data" },
  },
];

export function findTemplate(id: string): GameTemplate | undefined {
  return GAME_CATALOG.find((t) => t.id === id);
}
